### PR TITLE
Localization bugfix and compatibility with redmine 2.4

### PR DESCRIPTION
**Pull request by tofi86**
- removed `JournalObserver` patch for compatibility with redmine 2.4
  - _works for me with 2.4.4, ruby 1.9.3-p0, rails 3.2.17_
- Fixes bug where label in Admin > Roles > Settings wouldn't be displayed in current language
  - Localization didn't work because there was no matching string...
- Also: small changes in Readme

### CODE REVIEW

**Comment by tofi86** [comment]
Closing pull request. I published my changes with redmine 2.4.x compatibility and plugin default settings as "Silencer 2" in the redmine plugin repo: http://www.redmine.org/plugins/redmine_silencer

**Comment by Francewhoa** [comment]
Thanks  tofi86 :)

**Comment by tofi86** [comment]
You're welcome @Francewhoa :)
Feel free to leave a rating or comment on http://www.redmine.org/plugins/redmine_silencer

**Comment by Francewhoa** [comment]
Done, I added a positive review at http://www.redmine.org/plugins/redmine_silencer
I just discovered the Github notification icon, LOL :) To find your last reply.

**Pull request closed without merging**
